title: "Randy's Blog"
description: "My GitHub Pages site with Jekyll"
baseurl: ""        # Leave empty if using username.github.io
url: "https://randylenasty.github.io"
theme: minima      # Jekyll default theme

# Optional: Add markdown and plugins
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - tlm.md
